apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-bootstrap-provider-kubeadm-ignition
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
